export enum StrategyPriority {
  POLITENESS_REMOVAL = 10,
  STOPWORD_REMOVAL = 20,
  ABBREVIATION = 30,
  CONNECTOR_REMOVAL = 40,
  SINGLE_WORD_CONTRACTION = 50,
  CONTRACTION = 50,
}

export const PRIORITY = StrategyPriority;
